### PR TITLE
s3: combine all signature verification checks into a single function

### LINKED ISSUE #7320: S3 SignatureDoesNotMatch: PUT does not respect X-Forwarded-Prefix
With the following NGINX config:

```
        location /storage {
            # Strip the /storage prefix before forwarding to backend
            rewrite ^/storage(.*) $1 break;
            proxy_set_header X-Forwarded-Prefix /storage;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Ssl on;

            proxy_pass http://s3:8333;

            # Timeouts for long-running requests (e.g., large file uploads)
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;

        }
```

Notice `X-Forwarded-Prefix /storage`.

I try uploading a file to the bucket.

These are my debug logs from my Python script: (notice the GET and PUT with /storage prefix).

Below are the debug logs I added [here](https://github.com/seaweedfs/seaweedfs/blob/81c96ec71b4df6ffdc333f23d659fe5d3b10d6f8/weed/s3api/chunked_reader_v4.go#L49) and [here](https://github.com/seaweedfs/seaweedfs/blob/81c96ec71b4df6ffdc333f23d659fe5d3b10d6f8/weed/s3api/auth_signature_v4.go#L248).

Notice how the GET still has `/storage` prefix,  while the PUT doesn't. GET gets handled by the first logged  method `verifySignatureWithPath`, and PUT by the second method `calculateSeedSignature`. 

## Python botocore logs

```
DEBUG:botocore.hooks:Event before-sign.s3.ListObjectsV2: calling handler <function _set_extra_headers_for_unsigned_request at 0x72e4bd0285e0>
DEBUG:botocore.hooks:Event before-sign.s3.ListObjectsV2: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <aiobotocore.utils.AioS3ExpressIdentityResolver object at 0x72e4b7a674d0>>
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:
GET
/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720
encoding-type=url&list-type=2&max-keys=1
host:octopize.local
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20251013T141757Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20251013T141757Z
20251013/eu-west-3/s3/aws4_request
838d4422fb84e464fd5d05b9ccdccd424f28c74572af9214d79950c2a26d26a4
DEBUG:botocore.auth:Signature:
33b1d775994eb21a731f395d1cbced31e1e0248aa3ba4a0ec80b8fb20af62265
DEBUG:botocore.hooks:Event request-created.s3.ListObjectsV2: calling handler <function add_retry_headers at 0x72e4bd017ce0>
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://octopize.local/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720?list-type=2&max-keys=1&encoding-type=url, headers={'User-Agent': b'aiobotocore/2.22.0 md/Botocore#1.37.3 ua/2.0 os/linux#6.14.0-33-generic md/arch#x86_64 lang/python#3.13.1 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.37.3', 'X-Amz-Date': b'20251013T141757Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=K2MXEGPPUIPD5UNJCVUI2/20251013/eu-west-3/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=33b1d775994eb21a731f395d1cbced31e1e0248aa3ba4a0ec80b8fb20af62265', 'amz-sdk-invocation-id': b'2c308bcc-e409-4ddb-8eae-d135826103f1', 'amz-sdk-request': b'attempt=1'}>
DEBUG:botocore.hooks:Event before-parse.s3.ListObjectsV2: calling handler <function _handle_200_error at 0x72e4bd0282c0>
DEBUG:botocore.hooks:Event before-parse.s3.ListObjectsV2: calling handler <function handle_expires_header at 0x72e4bd0280e0>
DEBUG:botocore.parsers:Response headers: {'server': 'nginx/1.27.3', 'date': 'Mon, 13 Oct 2025 14:17:57 GMT', 'content-type': 'application/xml', 'content-length': '489', 'connection': 'keep-alive', 'accept-ranges': 'bytes', 'x-amz-request-id': '1760365077164982636', 'strict-transport-security': 'max-age=31536000; preload', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY'}
DEBUG:botocore.parsers:Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>fb14c3d7-84fc-4bc3-a4d3-43df62818720</Name><Prefix></Prefix><MaxKeys>1</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>30d/</Key><ETag>&#34;d41d8cd98f00b204e9800998ecf8427e-0&#34;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass><LastModified>2025-10-13T13:19:20Z</LastModified></Contents><EncodingType>url</EncodingType><KeyCount>1</KeyCount></ListBucketResult>'
DEBUG:botocore.hooks:Event needs-retry.s3.ListObjectsV2: calling handler <function _update_status_code at 0x72e4bd028400>
DEBUG:botocore.hooks:Event needs-retry.s3.ListObjectsV2: calling handler <aiobotocore.retryhandler.AioRetryHandler object at 0x72e4b7a67230>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:botocore.hooks:Event needs-retry.s3.ListObjectsV2: calling handler <bound method AioS3RegionRedirectorv2.redirect_from_error of <aiobotocore.utils.AioS3RegionRedirectorv2 object at 0x72e4b7a67380>>
DEBUG:botocore.hooks:Event after-call.s3.ListObjectsV2: calling handler <function decode_list_object_v2 at 0x72e4bd0171a0>
DEBUG:s3fs:CALL: put_object - () - {'Bucket': 'fb14c3d7-84fc-4bc3-a4d3-43df62818720', 'Key': '30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv'}
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x72e4bd016980>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x72e4bd015c60>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x72e4bd017380>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x72e4bd015bc0>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x72e4bd017d80>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <aiobotocore.utils.AioS3RegionRedirectorv2 object at 0x72e4b7a67380>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method ClientCreator._inject_s3_input_parameters of <aiobotocore.client.AioClientCreator object at 0x72e4bcbfea50>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x72e4bd0159e0>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function _handle_request_validation_mode_member at 0x72e4bd028540>
DEBUG:botocore.hooks:Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x72e4bd017f60>
DEBUG:botocore.hooks:Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <aiobotocore.utils.AioS3RegionRedirectorv2 object at 0x72e4b7a67380>>
DEBUG:aiobotocore.regions:Calling endpoint provider with parameters: {'Bucket': 'fb14c3d7-84fc-4bc3-a4d3-43df62818720', 'Region': 'eu-west-3', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://octopize.local/storage', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': False, 'Key': '30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv', 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
DEBUG:aiobotocore.regions:Endpoint provider result: https://octopize.local/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720
DEBUG:botocore.regions:Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
DEBUG:botocore.regions:Selected auth type "v4" as "v4" with signing context params: {'region': 'eu-west-3', 'signing_name': 's3', 'disableDoubleEncoding': True}
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x72e4bd015f80>
DEBUG:botocore.handlers:Adding expect 100 continue header to request.
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <bound method S3ExpressIdentityResolver.apply_signing_cache_key of <aiobotocore.utils.AioS3ExpressIdentityResolver object at 0x72e4b7a674d0>>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function add_recursion_detection_header at 0x72e4bd014a40>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function add_query_compatibility_header at 0x72e4bd0284a0>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x72e4bd0174c0>
DEBUG:botocore.endpoint:Making request for OperationModel(name=PutObject) with params: {'url_path': '/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'aiobotocore/2.22.0 md/Botocore#1.37.3 ua/2.0 os/linux#6.14.0-33-generic md/arch#x86_64 lang/python#3.13.1 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.37.3', 'Expect': '100-continue', 'Transfer-Encoding': 'chunked', 'Content-Encoding': 'aws-chunked', 'X-Amz-Trailer': 'x-amz-checksum-crc32', 'X-Amz-Decoded-Content-Length': '14335', 'x-amz-sdk-checksum-algorithm': 'CRC32'}, 'body': <aiobotocore.httpchecksum.AioAwsChunkedWrapper object at 0x72e4b5d60cd0>, 'auth_path': '/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv', 'url': 'https://octopize.local/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv', 'context': {'client_region': 'eu-west-3', 'client_config': <aiobotocore.config.AioConfig object at 0x72e4bcdcbb10>, 'has_streaming_input': True, 'auth_type': 'v4', 'unsigned_payload': None, 's3_redirect': {'redirected': False, 'bucket': 'fb14c3d7-84fc-4bc3-a4d3-43df62818720', 'params': {'Bucket': 'fb14c3d7-84fc-4bc3-a4d3-43df62818720', 'Key': '30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv', 'Body': <_io.BytesIO object at 0x72e4b5fbd800>}}, 'input_params': {'Bucket': 'fb14c3d7-84fc-4bc3-a4d3-43df62818720', 'Key': '30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv'}, 'signing': {'region': 'eu-west-3', 'signing_name': 's3', 'disableDoubleEncoding': True}, 'endpoint_properties': {'authSchemes': [{'disableDoubleEncoding': True, 'name': 'sigv4', 'signingName': 's3', 'signingRegion': 'eu-west-3'}]}, 'checksum': {'request_algorithm_header': {'name': 'x-amz-sdk-checksum-algorithm', 'value': 'CRC32'}, 'request_algorithm': {'algorithm': 'crc32', 'in': 'trailer', 'name': 'x-amz-checksum-crc32'}}}}
DEBUG:botocore.hooks:Event request-created.s3.PutObject: calling handler <bound method AioRequestSigner.handler of <aiobotocore.signers.AioRequestSigner object at 0x72e4b7a652b0>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x72e4bd015800>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <function remove_arn_from_signing_path at 0x72e4bd017ec0>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <function _set_extra_headers_for_unsigned_request at 0x72e4bd0285e0>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <aiobotocore.utils.AioS3ExpressIdentityResolver object at 0x72e4b7a674d0>>
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:
PUT
/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv

content-encoding:aws-chunked
host:octopize.local
x-amz-content-sha256:STREAMING-UNSIGNED-PAYLOAD-TRAILER
x-amz-date:20251013T141757Z
x-amz-decoded-content-length:14335
x-amz-sdk-checksum-algorithm:CRC32
x-amz-trailer:x-amz-checksum-crc32

content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer
STREAMING-UNSIGNED-PAYLOAD-TRAILER
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20251013T141757Z
20251013/eu-west-3/s3/aws4_request
676e1f8eb6bfc2438c26b625644355c54fc675665bff78cce3294243d67a7f8d
DEBUG:botocore.auth:Signature:
03357a375bcb43a032df9ca85bbe8317ff18c58a55923338bc3e0a8353857299
DEBUG:botocore.hooks:Event request-created.s3.PutObject: calling handler <function add_retry_headers at 0x72e4bd017ce0>
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=https://octopize.local/storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv, headers={'User-Agent': b'aiobotocore/2.22.0 md/Botocore#1.37.3 ua/2.0 os/linux#6.14.0-33-generic md/arch#x86_64 lang/python#3.13.1 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.37.3', 'Expect': b'100-continue', 'Transfer-Encoding': b'chunked', 'Content-Encoding': b'aws-chunked', 'X-Amz-Trailer': b'x-amz-checksum-crc32', 'X-Amz-Decoded-Content-Length': b'14335', 'x-amz-sdk-checksum-algorithm': b'CRC32', 'X-Amz-Date': b'20251013T141757Z', 'X-Amz-Content-SHA256': b'STREAMING-UNSIGNED-PAYLOAD-TRAILER', 'Authorization': b'AWS4-HMAC-SHA256 Credential=K2MXEGPPUIPD5UNJCVUI2/20251013/eu-west-3/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer, Signature=03357a375bcb43a032df9ca85bbe8317ff18c58a55923338bc3e0a8353857299', 'amz-sdk-invocation-id': b'b84d9f41-1fba-49cc-bd27-bfcc2591c905', 'amz-sdk-request': b'attempt=1'}>
DEBUG:botocore.hooks:Event before-parse.s3.PutObject: calling handler <function _handle_200_error at 0x72e4bd0282c0>
DEBUG:botocore.hooks:Event before-parse.s3.PutObject: calling handler <function handle_expires_header at 0x72e4bd0280e0>
DEBUG:botocore.parsers:Response headers: {'server': 'nginx/1.27.3', 'date': 'Mon, 13 Oct 2025 14:17:57 GMT', 'content-type': 'application/xml', 'content-length': '577', 'connection': 'keep-alive', 'accept-ranges': 'bytes', 'x-amz-request-id': '1760365077197868685', 'strict-transport-security': 'max-age=31536000; preload', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY'}
DEBUG:botocore.parsers:Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv</Resource><RequestId>1760365077197842304</RequestId><Key>30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv</Key><BucketName>fb14c3d7-84fc-4bc3-a4d3-43df62818720</BucketName></Error>'
DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <function _update_status_code at 0x72e4bd028400>
DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <aiobotocore.retryhandler.AioRetryHandler object at 0x72e4b7a67230>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <bound method AioS3RegionRedirectorv2.redirect_from_error of <aiobotocore.utils.AioS3RegionRedirectorv2 object at 0x72e4b7a67380>>
DEBUG:s3fs:Client error (maybe retryable): An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

## Seaweedfs logs

```
s3-1   | I1013 14:17:57.164166 auth_credentials.go:542 checking if user_integration can perform Write on bucket 'fb14c3d7-84fc-4bc3-a4d3-43df62818720/'
s3-1   | I1013 14:17:57.164206 auth_signature_v4.go:255 Canonical Request:
s3-1   | GET
s3-1   | /storage/fb14c3d7-84fc-4bc3-a4d3-43df62818720
s3-1   | encoding-type=url&list-type=2&max-keys=1
s3-1   | host:octopize.local
s3-1   | x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
s3-1   | x-amz-date:20251013T141757Z
s3-1   | 
s3-1   | host;x-amz-content-sha256;x-amz-date
s3-1   | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
s3-1   | I1013 14:17:57.164221 auth_signature_v4.go:260 String to Sign:
s3-1   | AWS4-HMAC-SHA256
s3-1   | 20251013T141757Z
s3-1   | 20251013/eu-west-3/s3/aws4_request
s3-1   | 838d4422fb84e464fd5d05b9ccdccd424f28c74572af9214d79950c2a26d26a4
s3-1   | I1013 14:17:57.164241 auth_signature_v4.go:265 Signing Key:
s3-1   | 19074c990a8be22cc5b879103771fb83a1d0f9f4524a5a20af69efda0894e401
s3-1   | I1013 14:17:57.164251 auth_signature_v4.go:270 Calculated Signature:
s3-1   | 33b1d775994eb21a731f395d1cbced31e1e0248aa3ba4a0ec80b8fb20af62265
s3-1   | I1013 14:17:57.164255 auth_signature_v4.go:272 Provided Signature:
s3-1   | 33b1d775994eb21a731f395d1cbced31e1e0248aa3ba4a0ec80b8fb20af62265
s3-1   | I1013 14:17:57.164264 auth_credentials.go:486 user name: user_integration actions: [Read:fb14c3d7-84fc-4bc3-a4d3-43df62818720/* Write:fb14c3d7-84fc-4bc3-a4d3-43df62818720/* List:fb14c3d7-84fc-4bc3-a4d3-43df62818720/*], action: List
s3-1   | I1013 14:17:57.164277 auth_credentials.go:542 checking if user_integration can perform List on bucket 'fb14c3d7-84fc-4bc3-a4d3-43df62818720/'
s3-1   | I1013 14:17:57.164284 auth_credentials.go:420 auth error: 0
s3-1   | I1013 14:17:57.164295 s3api_object_handlers_list.go:54 ListObjectsV2Handler fb14c3d7-84fc-4bc3-a4d3-43df62818720
s3-1   | I1013 14:17:57.164999 error_handler.go:121 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3-1   | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>fb14c3d7-84fc-4bc3-a4d3-43df62818720</Name><Prefix></Prefix><MaxKeys>1</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>30d/</Key><ETag>&#34;d41d8cd98f00b204e9800998ecf8427e-0&#34;</ETag><Size>0</Size><StorageClass>STANDARD</StorageClass><LastModified>2025-10-13T13:19:20Z</LastModified></Contents><EncodingType>url</EncodingType><KeyCount>1</KeyCount></ListBucketResult>
s3-1   | I1013 14:17:57.197615 auth_credentials.go:457 unsigned streaming upload
s3-1   | I1013 14:17:57.197632 auth_credentials.go:420 auth error: 0
s3-1   | I1013 14:17:57.197646 s3api_object_handlers_put.go:73 PutObjectHandler: Starting PUT fb14c3d7-84fc-4bc3-a4d3-43df62818720//30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv (Auth: AWS4-HMAC-SHA256 Credential=K2MXEGPPUIPD5UNJCVUI2/...)
s3-1   | I1013 14:17:57.197657 s3api_object_handlers_put.go:74 PutObjectHandler fb14c3d7-84fc-4bc3-a4d3-43df62818720 /30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv
s3-1   | I1013 14:17:57.197668 chunked_reader_v4.go:170 creating a new newSignV4ChunkedReader
s3-1   | I1013 14:17:57.197675 chunked_reader_v4.go:189 streaming unsigned payload
s3-1   | I1013 14:17:57.197689 chunked_reader_v4.go:70 streaming unsigned payload
s3-1   | I1013 14:17:57.197701 auth_credentials.go:542 checking if user_integration can perform Write on bucket 'fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv'
s3-1   | I1013 14:17:57.197738 chunked_reader_v4.go:118 Canonical Request:
s3-1   | PUT
s3-1   | /fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv
s3-1   | 
s3-1   | content-encoding:aws-chunked
s3-1   | host:octopize.local
s3-1   | x-amz-content-sha256:STREAMING-UNSIGNED-PAYLOAD-TRAILER
s3-1   | x-amz-date:20251013T141757Z
s3-1   | x-amz-decoded-content-length:14335
s3-1   | x-amz-sdk-checksum-algorithm:CRC32
s3-1   | x-amz-trailer:x-amz-checksum-crc32
s3-1   | 
s3-1   | content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer
s3-1   | STREAMING-UNSIGNED-PAYLOAD-TRAILER
s3-1   | I1013 14:17:57.197753 chunked_reader_v4.go:124 String to Sign:
s3-1   | AWS4-HMAC-SHA256
s3-1   | 20251013T141757Z
s3-1   | 20251013/eu-west-3/s3/aws4_request
s3-1   | 6de111b0d6a299ccd001baafb86c3fb44b470f1800aa9d236c4534274b5c73cd
s3-1   | I1013 14:17:57.197772 chunked_reader_v4.go:130 Signing Key:
s3-1   | L�
s3-1   | ��,Ÿy7q������RJZ �i���
s3-1   | I1013 14:17:57.197787 chunked_reader_v4.go:136 Signature:
s3-1   | 94e0da3181fa61abe41fe38046c6538f5ff56741a870695902cf926cd57f5e7a
s3-1   | I1013 14:17:57.197795 chunked_reader_v4.go:142 Extracted access key id: K2MXEGPPUIPD5UNJCVUI2
s3-1   | I1013 14:17:57.197802 chunked_reader_v4.go:143 Extracted region: eu-west-3
s3-1   | I1013 14:17:57.197809 chunked_reader_v4.go:144 Extracted service: s3
s3-1   | I1013 14:17:57.197815 chunked_reader_v4.go:145 Extracted date: 20251013
s3-1   | I1013 14:17:57.197824 chunked_reader_v4.go:146 Extracted signed headers: [content-encoding host x-amz-content-sha256 x-amz-date x-amz-decoded-content-length x-amz-sdk-checksum-algorithm x-amz-trailer]
s3-1   | I1013 14:17:57.197837 chunked_reader_v4.go:147 Extracted signature: 03357a375bcb43a032df9ca85bbe8317ff18c58a55923338bc3e0a8353857299
s3-1   | I1013 14:17:57.197881 error_handler.go:121 status 403 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3-1   | <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/fb14c3d7-84fc-4bc3-a4d3-43df62818720/30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv</Resource><RequestId>1760365077197842304</RequestId><Key>30d/62b697f7-8725-4c23-8ff4-88fdd6ba1a31/fb14c3d7-84fc-4bc3-a4d3-43df62818720/input/wbcd.csv</Key><BucketName>fb14c3d7-84fc-4bc3-a4d3-43df62818720</BucketName></Error>
```

### PR DESCRIPTION
**Pull request by tcrasset**
Combining the signature verification checks into a single method called in `chunked_reader_v4.go` and `auth_signature_v4.go` makes sure that any fixes done to authentication are applied on both sides. This is the case of `X-Forward-Prefix` now too.

Closes #7320

## Summary by CodeRabbit

* **Refactor**
  * Unified Signature V4 verification into a single pipeline with forwarded-prefix-aware path handling and improved mismatch/time-skew logging.

* **Bug Fixes**
  * Fixed presigned URL expiry validation, tightened streaming payload validation, preserved trailing‑slash/key semantics when composing paths, and added explicit RequestTimeTooSkewed error.

* **Tests**
  * Added/updated auth and streaming tests covering forwarded-prefix path assembly, computed signatures, presigned expiry, and signed streaming uploads; removed some legacy streaming tests.

### CODE REVIEW

File: weed/s3api/auth_signature_v4.go [hunk 1]
```diff
@@ -154,248 +157,246 @@ func parseSignV4(v4Auth string) (sv signValues, aec s3err.ErrorCode) {
...
-		// Try signature verification with the forwarded prefix first.
-		// This handles cases where reverse proxies strip URL prefixes and add the X-Forwarded-Prefix header.
-		cleanedPath := buildPathWithForwardedPrefix(forwardedPrefix, req.URL.Path)
-		errCode = iam.verifySignatureWithPath(extractedSignedHeaders, hashedPayload, queryStr, cleanedPath, req.Method, foundCred.SecretKey, t, signV4Values)
+		cleanedPath := buildPathWithForwardedPrefix(forwardedPrefix, r.URL.Path)
+		calculatedSignature, errCode = verify(cleanedPath)
 		if errCode == s3err.ErrNone {
-			return identity, errCode
+			return identity, nil, calculatedSignature, authInfo, s3err.ErrNone
 		}
```
Comment (tcrasset) [inline weed/s3api/auth_signature_v4.go:258]: The fix for X-Forward-Prefix is now also done for PUT requests

File: weed/s3api/auth_signature_v4.go [hunk 2]
```diff
@@ -154,248 +157,246 @@ func parseSignV4(v4Auth string) (sv signValues, aec s3err.ErrorCode) {
...
+	stringToSign := getStringToSign(canonicalRequest, authInfo.Date, authInfo.Scope)
+	signingKey := getSigningKey(secretKey, authInfo.Date.Format(yyyymmdd), authInfo.Region, authInfo.Service)
 	newSignature := getSignature(signingKey, stringToSign)
 
-	// Verify if signature match.
-	if !compareSignatureV4(newSignature, signV4Values.Signature) {
-		return s3err.ErrSignatureDoesNotMatch
+	if !compareSignatureV4(newSignature, authInfo.Signature) {
+		glog.V(4).Infof("Signature mismatch. Details:\n- Canonical Request: %s\n- String to Sign: %s\n- Calculated Signature: %s\n- Provided Signature: %s",
+			canonicalRequest, stringToSign, newSignature, authInfo.Signature)
```
Comment (tcrasset) [inline weed/s3api/auth_signature_v4.go]: Do note the logging statement here on failure and very verbose output, useful for me debugging without rebuilding locally + deploying a docker image.

File: weed/s3api/auth_signature_v4.go [hunk 3]
```diff
@@ -154,236 +157,248 @@ func parseSignV4(v4Auth string) (sv signValues, aec s3err.ErrorCode) {
...
-			return nil, s3err.ErrMissingDateHeader
+	// 3. Perform permission check
+	if shouldCheckPermissions {
+		bucket, object := s3_constants.GetBucketAndObject(r)
+		action := s3_constants.ACTION_READ
+		if r.Method != http.MethodGet && r.Method != http.MethodHead {
+			action = s3_constants.ACTION_WRITE
+		}
+		if !identity.canDo(Action(action), bucket, object) {
+			return nil, nil, "", nil, s3err.ErrAccessDenied
```
Comment (tcrasset) [inline weed/s3api/auth_signature_v4.go:220]: I am only conditionally checking permissions now (iam does not, chunck_reader does). This is to conform with the changes in https://github.com/seaweedfs/seaweedfs/pull/7335
